import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavItem from "@/components/NavItem";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-black sticky top-0 left-0 p-4 z-50 w-full">
          <NavItem />
        </div>
        {children}
      </body>
    </html>
  );
}
